export const ORGANIZATION_TYPES=new Set(['Prospective owner/operator','Utility','Data-center developer','Industrial energy user','Reactor vendor','EPC or major supplier','Government/economic-development organization','Investor or lender','Legal, regulatory, engineering, or QA advisor','Other'])
export const PROJECT_STAGES=new Set(['Initial concept','Site screening','Pre-application','Application development','Licensing','Construction planning','Operations planning'])
export const OBJECTIVES=new Set(['Project viability','Reactor-technology evaluation','Site development','Licensing preparation','Owner/operator readiness','Evidence and traceability','Project diligence or financing','Other'])
export const SOURCES=new Set(['atlaseye.ai','lab.atlaseye.ai'])
const KEYS=new Set(['full_name','work_email','organization','role_title','organization_type','project_location','project_stage','primary_objective','project_description','principal_question','preferred_contact_method','phone','consent','website','request_id','source'])
const CONTROL=/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f\u2028\u2029]/u
const INJECTION=/(?:<\s*\/?\s*(?:script|iframe|object|embed|style)|javascript\s*:|data\s*:\s*text\/html|\r|\n)/iu
const EMAIL=/^[A-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[A-Z0-9](?:[A-Z0-9-]{0,61}[A-Z0-9])?(?:\.[A-Z0-9](?:[A-Z0-9-]{0,61}[A-Z0-9])?)+$/iu
const PHONE=/^\+?[0-9 ()\-.]{7,30}$/u
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/iu
const text=(v,min,max,optional=false)=>{if(typeof v!=='string')throw Error('invalid');const n=v.normalize('NFC').trim();if((!optional&&n.length<min)||n.length>max||CONTROL.test(n)||INJECTION.test(n))throw Error('invalid');return n}
export function validateInquiry(input){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).some(k=>!KEYS.has(k))||Object.keys(input).length!==KEYS.size)throw Error('invalid');const out={...input};out.full_name=text(input.full_name,1,100);out.work_email=text(input.work_email,3,254).toLowerCase();if(!EMAIL.test(out.work_email))throw Error('invalid');out.organization=text(input.organization,1,120);out.role_title=text(input.role_title,0,100,true);out.project_location=text(input.project_location,0,120,true);out.project_description=text(input.project_description,10,1200);out.principal_question=text(input.principal_question,5,800);out.phone=text(input.phone,0,30,true);if(!ORGANIZATION_TYPES.has(input.organization_type)||!PROJECT_STAGES.has(input.project_stage)||!OBJECTIVES.has(input.primary_objective)||!SOURCES.has(input.source)||!['email','phone'].includes(input.preferred_contact_method)||input.consent!==true||typeof input.website!=='string'||input.website.length>0||!UUID.test(input.request_id)||(input.preferred_contact_method==='phone'&&!PHONE.test(out.phone))||(out.phone&&!PHONE.test(out.phone)))throw Error('invalid');return out}
export const escapeHtml=v=>v.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')
export function renderInquiry(v){const rows=[['Name',v.full_name],['Work email',v.work_email],['Organization',v.organization],['Role/title',v.role_title||'Not provided'],['Organization type',v.organization_type],['Project location',v.project_location||'Not provided'],['Project stage',v.project_stage],['Primary objective',v.primary_objective],['Description',v.project_description],['Principal question',v.principal_question],['Preferred contact',v.preferred_contact_method],['Phone',v.phone||'Not provided'],['Source',v.source]];return{subject:'Atlas Nuclear project-readiness review request',html:'<h2>Atlas Nuclear project-readiness review request</h2>'+rows.map(([k,x])=>`<p><strong>${escapeHtml(k)}:</strong> ${escapeHtml(x)}</p>`).join(''),text:'Atlas Nuclear project-readiness review request\n\n'+rows.map(([k,x])=>`${k}: ${x}`).join('\n')}}
