import { useEffect, useState } from 'react'
import { createObjective, gadgetSession, objectiveOverview, objectiveWork, continueObjective } from '../services/gadgetApi.js'
import './GadgetCockpit.css'

const specialists = ['Evidence', 'Regulatory', 'Siting', 'Fuel', 'Transportation', 'Supply Chain', 'Quality', 'R&D']
const entries = (value, empty) => value?.length ? value : [{ task: empty, status: 'WAITING_CONTEXT', reason: 'No server-backed record is available yet.' }]

export default function GadgetCockpit() {
  const [session, setSession] = useState({ loading: true, authenticated: false })
  const [objective, setObjective] = useState(''); const [state, setState] = useState(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  useEffect(() => { gadgetSession().then(value => setSession({ loading: false, ...value })).catch(() => setSession({ loading: false, authenticated: false, unavailable: true })) }, [])
  async function refresh(id = state?.objective_id) { if (!id) return; const [overview, work] = await Promise.all([objectiveOverview(id), objectiveWork(id)]); setState({ ...overview, work }) }
  async function submit(event) { event.preventDefault(); if (!session.authenticated || !objective.trim() || busy) return; setBusy(true); setError(''); try { const result = await createObjective(objective.trim(), session.csrf); setObjective(''); await refresh(result.objective_id) } catch (cause) { setError(cause.message) } finally { setBusy(false) } }
  async function continueWork() { if (!state?.objective_id || busy) return; setBusy(true); setError(''); try { await continueObjective(state.objective_id, session.csrf); await refresh() } catch (cause) { setError(cause.message) } finally { setBusy(false) } }
  return <main className="gadget-cockpit" data-testid="gadget-cockpit"><aside className="atlas-rail"><strong>AtlasEye</strong><span>MISSION CONTROL</span><span>PRIVATE PREVIEW</span></aside><section className="cockpit-main"><header className="cockpit-header"><p>GOVERNED PROJECT WORKSPACE</p><h1>Gadget</h1><span>Objective intake and safe continuation. Human review remains required.</span></header>
    {!session.loading && !session.authenticated ? <section className="cockpit-auth"><h2>Private workforce access required</h2><p>Sign in to create or inspect governed objectives.</p>{!session.unavailable && <a href="/api/gadget/auth/start?returnTo=%2Fmission-control%2F">Sign in to Gadget</a>}</section> : <><form className="objective-composer" onSubmit={submit}><label htmlFor="objective">What governed objective should Gadget coordinate?</label><textarea id="objective" value={objective} onChange={e => setObjective(e.target.value)} maxLength="2000" placeholder="Describe the bounded objective; project scope is resolved on the server." disabled={busy || !session.authenticated}/><button disabled={busy || !objective.trim() || !session.authenticated}>{busy ? 'Working…' : 'Create governed objective'}</button></form>
    {state ? <><section className="current-objective"><p>CURRENT OBJECTIVE</p><h2>{state.objective?.attributes?.objective_text || state.objective?.objective_text || 'Governed objective'}</h2><button onClick={continueWork} disabled={busy}>Continue safe work</button></section><section className="state-grid"><State title="Working" items={entries(state.working, 'No active server-backed work.')} /><State title="Needs You" items={entries(state.needs_you, 'No human action record is currently returned.')} /><State title="Holds" items={entries(state.holds, 'No hold record is currently returned.')} /></section><section className="context"><h2>Project context</h2><p>{state.project_context?.project_id || 'Not returned'}</p><p>{state.project_context?.scope || 'Server-resolved scope pending.'}</p><h2>Recent governed activity</h2>{entries(state.recent_activity, 'No recent server-backed activity.').map((item, i) => <p key={i}>{item.task || item.title} — {item.status}</p>)}</section></> : <section className="current-objective empty"><h2>No objective selected</h2><p>Create an authenticated, bounded objective to populate work, evidence, and decision state from the private BFF.</p></section>}</>}
  </section><aside className="cockpit-detail"><h2>Specialists</h2><div className="specialist-strip">{(state?.specialists?.map(x => x.label) || specialists).slice(0, 8).map(name => <span key={name}>{name}</span>)}</div><h2>Work / Evidence / Decisions</h2><p>{state?.evidence_summary?.note || 'Evidence summary is returned after an objective is selected.'}</p><p>{state?.decision_summary?.note || 'Decision summary is returned after an objective is selected.'}</p><p className="detail-drawer">Detail drawer: select a server-backed work item when available.</p>{error && <p role="alert">{error}</p>}</aside></main>
}
function State({ title, items }) { return <section><h2>{title}</h2>{items.map((item, index) => <article key={index}><strong>{item.task || item.title || item.task_id}</strong><span>{item.status}</span><p>{item.reason || item.blocker_or_next_step || 'Server-backed record.'}</p></article>)}</section> }
