import { categories } from './legalBasis.js'
const esc = value => String(value ?? '').replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#39;')
const readable = value => String(value ?? '').replaceAll('_', ' ')
export function basisHtml(basis) {
  return `<section class="basis-content"><p><strong>Stable ID:</strong> ${esc(basis.id)} · ${esc(categories[basis.category])}</p><p><strong>Authority verification:</strong> ${esc(basis.authorityStatus)}</p>${basis.authorities.map(a => `<p><strong>${esc(categories[a.category])} · ${esc(a.issuingBody)}:</strong> ${a.url ? `<a href="${esc(a.url)}" target="_blank" rel="noreferrer">${esc(basis.provision || a.provision)}</a>` : esc(a.provision)} · ${esc(a.id)}<br>${esc(a.meaning)}<br><strong>Source version/status:</strong> ${esc(a.version)}; ${esc(a.sourceStatus)} / ${esc(a.legalStatus)}. <strong>Verified:</strong> ${esc(a.verifiedAt || 'Verification pending')}. <strong>Effective date:</strong> ${esc(a.effectiveDate || 'Not separately established; see source version/status')}<br>${esc(a.bindingStatus)} ${esc(a.limitations)}</p>`).join('')}<p><strong>Applicability:</strong> ${esc(basis.applicability.state)} — ${esc(basis.applicability.reason)}</p><p><strong>Facts and provenance:</strong></p><ul>${basis.facts.map(f => `<li>${esc(readable(f.key))}: ${esc(readable(f.value) || 'Missing')} · ${esc(categories[f.category])} · ${esc(f.provenance)} · Unverified</li>`).join('')}</ul><p><strong>Exceptions / unresolved questions:</strong> ${esc(basis.exceptions)}</p><p><strong>Supporting evidence expected:</strong> ${esc(basis.evidence)} ${esc(basis.evidenceOrigin)}</p><p><strong>AtlasEye has established:</strong> ${esc(basis.established)}</p><p><strong>Qualified review remains:</strong> ${esc(basis.humanReview)}</p></section>`
}
export function traceabilityHtml(snapshot) {
  if (!snapshot) return '<p>Historical authority basis verification pending: this legacy decision did not capture a source snapshot. Current sources have not been substituted.</p>'
  return `<p>Authority snapshot ${esc(snapshot.version)} · project revision ${esc(snapshot.projectRevision)}</p>${snapshot.requirements.map(b => `<details><summary>${esc(b.id)} · ${esc(b.title)} · ${esc(b.applicability.state)}</summary>${basisHtml(b)}</details>`).join('')}`
}
export function traceabilityRows(snapshot, label = 'Current traceability') {
  if (!snapshot) return [[label, 'Historical authority basis verification pending; no original snapshot']]
  return [[label, snapshot.version, 'Project revision', snapshot.projectRevision], ['Stable item ID', 'Category', 'Authority IDs', 'Exact provisions', 'Official URLs', 'Authority verification', 'Source versions', 'Verified dates', 'Effective dates', 'Applicability', 'Applicability explanation', 'Facts / provenance', 'Unresolved questions', 'Expected evidence / origin', 'Review boundary'], ...snapshot.requirements.map(b => [b.id, categories[b.category], b.authorities.map(a => a.id).join('; '), b.provision || b.authorities.map(a => a.provision).join('; '), b.authorities.map(a => a.url).filter(Boolean).join('; '), b.authorityStatus, b.authorities.map(a => a.version).join('; '), b.authorities.map(a => a.verifiedAt || 'Verification pending').join('; '), b.authorities.map(a => a.effectiveDate || 'Not separately established').join('; '), b.applicability.state, b.applicability.reason, b.facts.map(f => `${readable(f.key)}: ${readable(f.value)} (${categories[f.category]}; ${f.provenance}; unverified)`).join('; '), b.exceptions, `${b.evidence} ${b.evidenceOrigin}`, b.humanReview])]
}
