// Human-reviewed source records. Network availability never changes legal status.
export const basisVersion = 'atlas-basis-2026-09-07.1'
export const categories = { A: 'Statute or regulation', B: 'Party/activity-specific license condition or order', C: 'Agency guidance', D: 'Industry standard', E: 'Customer-provided fact', F: 'Sample assumption', G: 'AtlasEye workflow control', H: 'Professional judgment or interpretation' }
const nrcUrl = section => `https://www.ecfr.gov/current/title-10/chapter-I/part-53/subpart-H/section-${section}`
const dotUrl = section => `https://www.ecfr.gov/current/title-49/subtitle-B/chapter-I/subchapter-C/part-${section.split('.')[0]}/${section.startsWith('173') ? 'subpart-I' : 'subpart-G'}/section-${section}`
const rule = (id, provision, title, url, meaning, extra = {}) => ({ id, category: 'A', issuingBody: id.startsWith('dot') ? 'DOT / PHMSA' : 'NRC', title, provision, url, meaning, effectiveDate: null, version: 'eCFR displayed through 2026-09-03', verifiedAt: '2026-09-07', sourceStatus: 'verified', legalStatus: 'effective', bindingStatus: 'Binding regulation only when its applicability conditions are met; this record is not an agency decision.', limitations: 'No automatic currency check after the recorded verification date. Only the described provision and bounded claim were checked.', ...extra })
export const authorities = {
  'atlas-workflow': { id: 'atlas-workflow', category: 'G', issuingBody: 'AtlasEye', title: 'Public demonstration evidence and review controls', provision: 'AtlasEye workflow v3', url: '', meaning: 'AtlasEye requests relevant, versioned records and an explicit bounded review before simulated acceptance.', effectiveDate: null, version: basisVersion, verifiedAt: '2026-09-07', sourceStatus: 'verified', legalStatus: 'nonbinding', bindingStatus: 'Software behavior, not law, a contract, or agency approval.', limitations: 'Browser-local sample assessment only.' },
  'nrc-general': rule('nrc-general', '10 CFR § 53.1109(a)–(e)', 'Applicant general information', nrcUrl('53.1109'), 'The provision requires applicant identity, organization and requested-license information.', { effectiveDate: '2026-04-29' }),
  'nrc-finance': rule('nrc-finance', '10 CFR § 53.1413, introductory text and (a)–(b)', 'COL general and financial information', nrcUrl('53.1413'), 'The provision addresses construction, fuel-cycle and operating-cost financial information, subject to its electric-utility exception.', { effectiveDate: '2026-04-29' }),
  'nrc-safety': rule('nrc-safety', '10 CFR § 53.1416(a), introductory text', 'COL final safety analysis report', nrcUrl('53.1416'), 'The provision requires an FSAR addressing the facility, operating limits and safety analysis. A preliminary summary is not that completed analysis.', { effectiveDate: '2026-04-29' }),
  'nrc-environment': rule('nrc-environment', '10 CFR § 53.1419(a)(1)(i)–(ii)', 'COL environmental report', nrcUrl('53.1419'), 'The environmental-report path depends on whether a limited work authorization is requested.', { effectiveDate: '2026-04-29' }),
  'nrc-environment-content': rule('nrc-environment-content', '10 CFR § 51.50(c)', 'Environmental report at combined-license stage', 'https://www.ecfr.gov/current/title-10/chapter-I/part-51/subpart-A/subject-group-ECFR225cbb5e51bb30b/section-51.50', 'A COL applicant submits a separate environmental report; referenced approvals and site changes affect its content.', { limitations: 'Only the duty to provide the report was checked. The incorporated analyses, §§ 51.45, 51.51, 51.52 and any limited-work path are outside this implementation.' }),
  'nrc-eligibility': rule('nrc-eligibility', '10 CFR § 53.1118, introductory text and (a)–(b)', 'Ineligibility of certain applicants', nrcUrl('53.1118'), 'Foreign ownership or control requires assessment of the provision, including both its Commission-determination and listed-country conditions. AtlasEye does not determine eligibility.', { effectiveDate: '2026-04-29' }),
  'dot-hrcq': rule('dot-hrcq', '49 CFR § 173.403, Highway route controlled quantity (1)–(3); A1, A2 and normal/special form definitions', 'HRCQ definition', dotUrl('173.403'), 'HRCQ compares activity in a single package against the applicable A1/A2 multiple and absolute activity threshold. Mass and enrichment alone do not resolve it.', { limitations: 'No radionuclide activity calculation or § 173.433/§ 173.435 value assessment is implemented. This definition does not itself approve a route.' }),
  'dot-response-scope': rule('dot-response-scope', '49 CFR § 172.600(a)–(d)', 'Emergency response applicability', dotUrl('172.600'), 'The subpart covers hazardous-material transportation handling, with an exception for materials excepted from shipping papers.'),
  'dot-response': rule('dot-response', '49 CFR § 172.602(a)–(c)', 'Emergency response information', dotUrl('172.602'), 'The provision specifies incident-response information, its form and accessibility. A response organization or exercise record alone is not this information.', { effectiveDate: '2026-09-03', version: 'eCFR through 2026-09-03; (b)(1) amended by 91 FR 49325–49329, effective 2026-09-03' }),
  'dot-phone': rule('dot-phone', '49 CFR § 172.604(a)–(d)', 'Emergency response telephone number', dotUrl('172.604'), 'The offeror provides an available, knowledgeable emergency contact, subject to the listed exceptions.'),
}
const common = { permittedFindingStates: ['gap', 'conflict', 'review', 'supported', 'demo_accepted', 'stale', 'changes_requested', 'rejected'], humanReview: 'Qualified reviewers must establish legal applicability, authenticity and sufficiency. AtlasEye establishes only the displayed bounded checks; simulated acceptance is not NRC acceptance, shipment authorization, supplier qualification or NQA-1 certification.', evidenceOrigin: 'AtlasEye workflow choice: request a linked, versioned record to support the represented issue. File processing and citations never establish acceptance.' }
const req = (id, title, category, authorityIds, factKeys, exceptions, evidence, extra = {}) => ({ ...common, id, title, category, authorityIds, factKeys, exceptions, evidence, conditions: 'Use only the represented project and the current facts below.', ...extra })
export const requirements = {
  'p53-legal': req('p53-legal', 'Applicant identity', 'A', ['nrc-general'], ['legal-name', 'address', 'business', 'organization', 'citizenship', 'focd', 'license'], 'Entity form and any agency relationship determine the applicable paragraph of (d). Other application sections are outside the fourteen questions.', 'Applicant information and organization support.'),
  'p53-financial': req('p53-financial', 'Financial qualifications', 'A', ['nrc-finance', 'nrc-general'], ['license', 'financial'], 'Electric-utility status and the post-§ 53.1452 finding exception are not resolved by the intake.', 'Financial capacity plan, estimates and funding-source information; AtlasEye tracks a sample plan, not financial qualification.'),
  'p53-safety': req('p53-safety', 'Safety analysis content', 'A', ['nrc-safety'], ['license', 'safety'], 'Referenced design/site approvals and the full technical content are not assessed.', 'Controlled FSAR for actual application use; sample summary is preliminary.'),
  'p53-environment': req('p53-environment', 'Environmental information', 'A', ['nrc-environment', 'nrc-environment-content'], ['license', 'environment'], 'Limited work authorization and referenced permit facts are missing; complete environmental content is outside scope.', 'Separate environmental report; sample outline does not establish its adequacy.'),
  'p53-eligibility': req('p53-eligibility', 'Legal eligibility review', 'H', ['nrc-eligibility', 'nrc-general', 'atlas-workflow'], ['focd', 'organization', 'eligibility'], 'Ownership/control facts, country conditions and any Commission determination remain unverified.', 'Qualified legal reasoning and ownership records. A legal-review memo is an AtlasEye evidence choice, not a prescribed document.'),
  'trn-material': req('trn-material', 'Material and HRCQ facts', 'A', ['dot-hrcq'], ['material', 'form', 'enrichment', 'quantityValue', 'quantityUnit', 'hrcqStatus', 'hrcqBasis'], 'Activity per package, radionuclides and applicable activity values are missing. Resolve HRCQ facts selects a sample assumption only.', 'Activity and package threshold analysis; no real HRCQ calculation is supplied.'),
  'trn-response': req('trn-response', 'Emergency response information', 'A', ['dot-response-scope', 'dot-response', 'dot-phone', 'atlas-workflow'], ['material', 'routeProfile', 'emergencyEvidence'], 'Shipping-paper exceptions and offeror/handler roles are not established. Exercise records do not demonstrate all information or telephone requirements.', 'Response information and contact availability for real compliance; AtlasEye sample response/exercise evidence supports only the demo gate.'),
}
for (const [id, title, keys, evidence, exceptions] of [
  ['p53-records', 'Controlled record inventory', ['evidence'], 'Section-to-record inventory.', 'No legal document-control contract is represented.'],
  ['p53-reviews', 'Review status', ['reviews'], 'Responsible roles and open actions.', 'A review assignment is not an agency determination.'],
  ['p53-history', 'Application history', ['history'], 'Prior versions and decisions.', 'Browser history is not production regulatory recordkeeping.'],
  ['trn-package', 'Package compatibility', ['material', 'form', 'enrichment', 'quantityValue', 'quantityUnit'], 'The supplied package record covers exactly HALEU UF6, 19.75 wt%, 12 kgU.', 'Actual package certificate, authorized contents and transport permission are outside scope; no party-specific authority is supplied.'],
  ['trn-carrier', 'Carrier authority', ['routeProfile', 'carrierEvidence'], 'Sample carrier record plus scenario assessment.', 'Actual carrier permits, registration and operating authority are not verified.'],
  ['trn-route', 'Route and mode', ['origin', 'destination', 'routeProfile', 'hrcqStatus'], 'Route record for the stated Ohio-to-Pennsylvania highway scenario.', 'The former HRCQ citation defines a quantity; it does not establish route compliance. Actual routing law and maritime authority verification are pending outside this implementation.'],
  ['trn-security', 'Security and physical protection', ['routeProfile', 'securityEvidence'], 'Public sample security readiness record and scope selection.', 'No security plan sufficiency, applicable protection regime or license/order is verified.'],
  ['trn-execution', 'Shipment execution', ['routeProfile', 'executionEvidence'], 'Sample pre-departure record and scope assessment.', 'Actual inspections, measurements, shipping papers and package authorizations remain separate qualified checks.'],
  ['trn-reviewer', 'Governed reviewer', ['reviewer'], 'Explicit demonstration reviewer selection.', 'No real reviewer identity or authority is authenticated.'],
  ['sup-qap-current', 'Current quality program document', ['supplier', 'expectedQualityProgramIdentity', 'expectedQualityProgramVersion'], 'Matching Quality Program Manual Rev. C and supersession metadata.', 'No contract, license incorporation or NQA-1 edition/text was supplied or verified. No standard is treated as binding.'],
  ['sup-calibration', 'Calibration record sample', ['supplier', 'itemScope'], 'The supplied calibration sample linked to this supplier.', 'A single sample does not establish calibration-program effectiveness or full qualification.'],
  ['trn-governed-review', 'Bounded transportation review decision', ['material', 'routeProfile', 'reviewer'], 'Current evaluation fingerprint and the reviewed evidence versions.', 'Only simulated gate acceptance; all legal determinations remain separate.'],
  ['supplier-decision', 'Bounded supplier review decision', ['supplier', 'expectedQualityProgramVersion'], 'Reviewer explanation plus current quality program and calibration sample.', 'Professional reasoning is recorded as the reviewer’s judgment, never attributed to an agency.'],
  ['trn-maritime', 'Optional maritime/change scenario', ['routeProfile'], 'Scenario selections for added transport segments.', 'Outside the implemented legal scope: port, vessel, flag-state and destination authorities are verification pending.'],
]) requirements[id] = req(id, title, 'G', ['atlas-workflow'], keys, exceptions, evidence)
// Distinguish authority-prescribed information from Atlas-selected sample files.
for (const [id, origin] of Object.entries({
  'p53-legal': 'Direct authority: applicant information. AtlasEye choice: organization support file and version links.',
  'p53-financial': 'Direct authority: financial information described in § 53.1413. AtlasEye choice: the supplied preliminary plan and workflow review.',
  'p53-safety': 'Direct authority: FSAR under § 53.1416(a). AtlasEye choice: retain a preliminary sample summary as evidence of work in progress, not a completed FSAR.',
  'p53-environment': 'Direct authority: environmental report under §§ 53.1419(a)(1) and 51.50(c). AtlasEye choice: retain the sample outline without treating it as adequate.',
  'trn-material': 'Authority supplies a definition, not an AtlasEye intake duty. AtlasEye requests activity and package facts to support a future threshold analysis.',
  'trn-response': 'Direct authority: response information and applicable telephone duties. AtlasEye choice: the sample response/exercise record and assessment dropdown; these cannot prove all regulatory elements.',
})) requirements[id].evidenceOrigin = origin + ' A citation or attachment alone never establishes acceptance.'
export const questionProvisions = { 'legal-name': '(a)', address: '(b)', business: '(c)', organization: '(d)(3)(i)', citizenship: '(d)(3)(ii)', focd: '(d)(3)(iii)', license: '(e)' }
export const questionParents = { 'legal-name': 'p53-legal', address: 'p53-legal', business: 'p53-legal', organization: 'p53-legal', citizenship: 'p53-legal', focd: 'p53-legal', license: 'p53-legal', financial: 'p53-financial', safety: 'p53-safety', environment: 'p53-environment', eligibility: 'p53-eligibility', evidence: 'p53-records', reviews: 'p53-reviews', history: 'p53-history' }
for (const [key, parent] of Object.entries(questionParents)) requirements[`q-${key}`] = { ...requirements[parent], id: `q-${key}`, parent, title: `Intake: ${key}`, factKeys: [...new Set(['license', key, ...(questionProvisions[key]?.startsWith('(d)') ? ['organization'] : [])])], provision: questionProvisions[key] ? `10 CFR § 53.1109${questionProvisions[key]}` : null }

export function sourceSupport(ids, registry = authorities, at = '2026-09-07') {
  if (!ids?.length) return 'verification pending — no authority mapping'
  if (ids.some(id => !registry[id] || registry[id].sourceStatus !== 'verified')) return 'verification pending — missing or unverified authority'
  if (ids.some(id => registry[id].category === 'A' && (registry[id].legalStatus !== 'effective' || (registry[id].effectiveDate && registry[id].effectiveDate > at)))) return 'not established — provision is not effective binding law'
  return ids.some(id => registry[id].category === 'A') ? 'verified provision within stated limits' : 'nonstatutory basis'
}
export function applicabilityFor(record, project) {
  const facts = project.inputs || {}
  const id = record.parent || record.id
  if (id === 'trn-maritime') return facts.routeProfile === 'truck_only' ? { state: 'Not applicable', reason: 'Recorded route is highway only; no maritime segment is represented.' } : { state: 'Outside the implemented demo scope', reason: record.exceptions }
  const missing = record.factKeys.filter(key => !String(facts[key] ?? '').trim())
  if (missing.length) return { state: 'Applicability unresolved', reason: `Missing facts: ${missing.join(', ')}.` }
  if (id.startsWith('p53-') && record.category !== 'G') {
    if (!/\bCOL\b|combined license/i.test(facts.license || '')) return { state: 'Applicability unresolved', reason: 'The entered license request does not establish the represented Part 53 COL path.' }
    if (['p53-financial', 'p53-environment', 'p53-eligibility'].includes(id)) return { state: 'Applicability unresolved', reason: record.exceptions }
    if (record.provision?.includes('(d)') && !/LLC|corporation|association|limited liability/i.test(facts.organization || '')) return { state: 'Applicability unresolved', reason: 'The entered entity form does not establish the corporate/association paragraph; individual, partnership and agency alternatives need review.' }
  }
  if (['trn-material', 'trn-response'].includes(id)) return { state: 'Applicability unresolved', reason: record.exceptions }
  if (id.startsWith('trn-') && facts.routeProfile === 'truck_port_vessel') return { state: 'Outside the implemented demo scope', reason: 'Maritime selections exercise workflow invalidation; international legal applicability is not implemented.' }
  if (id === 'trn-package' && (facts.material !== 'HALEU' || facts.form !== 'UF6' || Number(facts.enrichment) !== 19.75 || Number(facts.quantityValue) !== 12 || facts.quantityUnit !== 'kgU')) return { state: 'Outside the implemented demo scope', reason: 'Facts differ from the only package content scope implemented (19.75 wt%, 12 kgU HALEU UF6). Reconsider evidence and prior review.' }
  return { state: 'Applicable within represented scope', reason: record.category === 'G' ? 'This AtlasEye workflow check is relevant to the represented project. Legal applicability is not established by it.' : 'Sample project uses the Part 53 COL preparation path. This is an information requirement, not a conclusion that the answer satisfies it.' }
}
export function basisFor(id, project, registry = authorities) {
  const record = requirements[id]
  if (!record) return { id, title: 'Unmapped item', category: 'H', authorities: [], authorityStatus: 'verification pending — missing requirement', applicability: { state: 'Applicability unresolved', reason: 'No reviewed mapping exists.' }, exceptions: 'Obtain a reviewed mapping.', facts: [], humanReview: common.humanReview, evidence: 'Not established', evidenceOrigin: common.evidenceOrigin, established: 'No legal conclusion established.' }
  return { ...record, basisVersion, authorities: record.authorityIds.map(key => registry[key] || { id: key, provision: 'Missing authority', category: 'H', sourceStatus: 'verification pending', limitations: 'Missing source record.' }), authorityStatus: sourceSupport(record.authorityIds, registry), applicability: applicabilityFor(record, project), facts: record.factKeys.map(key => ({ key, value: project.inputs?.[key] ?? '', category: project.factProvenance?.[key]?.category || 'E', provenance: project.factProvenance?.[key]?.provenance || 'Legacy browser entry; original provenance not recorded, not independently verified', verified: false })), established: 'AtlasEye records the displayed facts, links and workflow result. Source verification, legal applicability, evidence sufficiency and the review decision are separate.' }
}
export function snapshotBasis(project) {
  return structuredClone({ version: basisVersion, projectRevision: project.revision || 0, inputs: project.inputs, requirements: [...(project.requirements || []).map(r => r.id), ...(project.guided?.questions || []).map(q => `q-${q.id}`), ...(project.id === 'fuel-transport' ? ['trn-governed-review', 'trn-maritime'] : project.id === 'supplier-qualification' ? ['supplier-decision'] : [])].map(id => basisFor(id, project)) })
}
