export const presenterOpening = 'Atlas shows what is required, why it applies, what evidence supports your position, and what remains unresolved before your team moves forward.'
export const presenterSteps = [
  { label: 'ForgeWorks Safety-Related Valve Supplier Review', show: 'Mission Control → ForgeWorks Safety-Related Valve Supplier Review (project card)', say: 'This is a bounded supplier desk review. The starting blocker is a superseded quality program.', result: 'The project Overview shows the blocker and next action.', saved: 'If progress exists, inspect the current state. For a fresh story, use Reset saved demo and confirm; this resets all three browser projects.' },
  { label: 'Requirements', show: 'Requirements → Current quality program document', say: 'Revision B conflicts with the expected Revision C. Atlas keeps that conflict visible.', result: 'The requirement card shows Conflict, or the current reviewed state if already corrected.', saved: 'Use Evidence to inspect retained Revision B and its replacement history if corrected.' },
  { label: 'Basis for this control', show: 'Expand Basis for this control under Current quality program document.', say: 'This is an Atlas workflow control, not a statutory duty. No NQA-1 edition, contract or license incorporation has been verified.', result: 'The panel displays source category, facts, evidence expectation and review boundary.', saved: 'Opening this panel never changes or resets data.' },
  { label: 'Evidence', show: 'Evidence → select the quality program record; inspect content, version and linked requirement.', say: 'The file has an identity and a revision. Attachment alone does not establish that it supports this supplier.', result: 'The retained sample content and supersession metadata can be inspected.', saved: 'If Rev. C is already present, show the retained replacement history and current links.' },
  { label: 'Load sample evidence', show: 'Requirements → Load sample evidence in Current quality program document, then Calibration record sample. Simulated supplier review → Decision explanation → Simulate supplier acceptance.', say: 'We replace the represented issue and inspect both records. This explanation records a bounded simulated review; it does not qualify the supplier.', result: 'A current simulated decision records scope and evidence versions. Say: “Rev. C matches the expected sample identity and the calibration sample is linked; broader qualification remains open.”', saved: 'If already accepted, show the saved explanation and History. Avoid creating a duplicate decision just for the presentation.' },
  { label: 'Report', show: 'Report → Download HTML report → Download evidence/action register; optionally Print / save PDF.', say: 'The report preserves the finding, authority category, applicability, evidence versions and decision basis. Remaining work travels with the result.', result: 'Downloaded HTML and CSV include supporting legal/basis mapping and the original decision snapshot.', saved: 'Downloads reflect current progress and preserve earlier decisions as history.' },
]
