import { useEffect, useRef, useState } from 'react'
import './ReadinessReviewForm.css'

const ENDPOINT='https://nnudwaqrgtztmcrcwpxn.supabase.co/functions/v1/project-readiness-inquiry'
const ORGS=['Prospective owner/operator','Utility','Data-center developer','Industrial energy user','Reactor vendor','EPC or major supplier','Government/economic-development organization','Investor or lender','Legal, regulatory, engineering, or QA advisor','Other']
const STAGES=['Initial concept','Site screening','Pre-application','Application development','Licensing','Construction planning','Operations planning']
const OBJECTIVES=['Project viability','Reactor-technology evaluation','Site development','Licensing preparation','Owner/operator readiness','Evidence and traceability','Project diligence or financing','Other']
const EMPTY={full_name:'',work_email:'',organization:'',role_title:'',organization_type:'',project_location:'',project_stage:'',primary_objective:'',project_description:'',principal_question:'',preferred_contact_method:'email',phone:'',consent:false,website:''}

export default function ReadinessReviewForm({open,onClose}){
 const [form,setForm]=useState(EMPTY),[state,setState]=useState('idle'),[error,setError]=useState(''); const dialog=useRef(null),closeButton=useRef(null),priorFocus=useRef(null)
 useEffect(()=>{if(!open)return;priorFocus.current=document.activeElement;requestAnimationFrame(()=>{setState('idle');setError('');setForm(EMPTY);closeButton.current?.focus()});const keydown=e=>{if(e.key==='Escape'){e.preventDefault();onClose();return}if(e.key!=='Tab'||!dialog.current)return;const c=[...dialog.current.querySelectorAll('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),a[href]')];if(!c.length)return;if(e.shiftKey&&document.activeElement===c[0]){e.preventDefault();c.at(-1).focus()}else if(!e.shiftKey&&document.activeElement===c.at(-1)){e.preventDefault();c[0].focus()}};document.addEventListener('keydown',keydown);return()=>{document.removeEventListener('keydown',keydown);priorFocus.current?.focus()}},[open,onClose])
 if(!open)return null
 const update=e=>setForm(v=>({...v,[e.target.name]:e.target.type==='checkbox'?e.target.checked:e.target.value}));const close=()=>{if(state!=='submitting')onClose()}
 const submit=async e=>{e.preventDefault();setState('submitting');setError('');const requestId=crypto.randomUUID();try{const r=await fetch(ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json','X-Atlas-Request-Id':requestId},body:JSON.stringify({...form,request_id:requestId,source:'atlaseye.ai'})});const b=await r.json().catch(()=>({}));if(!r.ok||!b.ok||typeof b.reference!=='string')throw Error();setState('success')}catch{setState('failure');setError('We could not deliver your request. Please try again later.')}}
 return <div className="modal-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><section ref={dialog} className="review-dialog" role="dialog" aria-modal="true" aria-labelledby="review-dialog-title" aria-describedby="review-dialog-intro"><button ref={closeButton} className="dialog-close" type="button" onClick={close} aria-label="Close request form">×</button>
 {state==='success'?<div className="success-panel" role="status" aria-live="polite"><p className="eyebrow">REQUEST RECEIVED</p><h2 id="review-dialog-title">Thank you.</h2><p>Your project-readiness request was received. Atlas Nuclear will contact you using the information provided. No project evidence or governed record was created.</p><button className="button primary" type="button" onClick={onClose}>Return to Atlas</button></div>:<><p className="eyebrow">PROJECT-READINESS REVIEW</p><h2 id="review-dialog-title">Request an Atlas Nuclear project-readiness review</h2><p id="review-dialog-intro">Tell us briefly about your organization and proposed SMR project. We will contact you to discuss your current stage, evidence, principal uncertainties, and the next credible project decision.</p><p className="submission-warning"><b>Do not submit safeguards information, security-sensitive information, export-controlled technical data, proprietary reactor information, or controlled project records through this form.</b></p>
 <form onSubmit={submit}><div className="form-grid">
 <label>Full name *<input name="full_name" value={form.full_name} onChange={update} required maxLength="100" autoComplete="name"/></label><label>Work email *<input name="work_email" value={form.work_email} onChange={update} required maxLength="254" type="email" autoComplete="email"/></label><label>Organization *<input name="organization" value={form.organization} onChange={update} required maxLength="120" autoComplete="organization"/></label><label>Role/title <small>optional</small><input name="role_title" value={form.role_title} onChange={update} maxLength="100" autoComplete="organization-title"/></label>
 <label>Organization type *<select name="organization_type" value={form.organization_type} onChange={update} required><option value="">Select one</option>{ORGS.map(v=><option key={v}>{v}</option>)}</select></label><label>Project location <small>optional</small><input name="project_location" value={form.project_location} onChange={update} maxLength="120"/></label><label>Project stage *<select name="project_stage" value={form.project_stage} onChange={update} required><option value="">Select one</option>{STAGES.map(v=><option key={v}>{v}</option>)}</select></label><label>Primary objective *<select name="primary_objective" value={form.primary_objective} onChange={update} required><option value="">Select one</option>{OBJECTIVES.map(v=><option key={v}>{v}</option>)}</select></label>
 <label className="wide">Short project description *<textarea name="project_description" value={form.project_description} onChange={update} required minLength="10" maxLength="1200" rows="4"/></label><label className="wide">Principal question or concern *<textarea name="principal_question" value={form.principal_question} onChange={update} required minLength="5" maxLength="800" rows="3"/></label>
 <fieldset><legend>Preferred contact method *</legend><label className="radio"><input type="radio" name="preferred_contact_method" value="email" checked={form.preferred_contact_method==='email'} onChange={update}/> Email</label><label className="radio"><input type="radio" name="preferred_contact_method" value="phone" checked={form.preferred_contact_method==='phone'} onChange={update}/> Phone</label></fieldset><label>Phone {form.preferred_contact_method==='phone'?'*':<small>optional</small>}<input name="phone" value={form.phone} onChange={update} required={form.preferred_contact_method==='phone'} maxLength="30" type="tel" autoComplete="tel"/></label>
 </div><label className="honeypot" aria-hidden="true">Website<input name="website" value={form.website} onChange={update} tabIndex="-1" autoComplete="off"/></label><label className="consent"><input type="checkbox" name="consent" checked={form.consent} onChange={update} required/><span>I agree that Atlas Nuclear may contact me about this project-readiness request. *</span></label><p className="privacy-copy">Atlas Nuclear uses this information only to respond to your inquiry. Submitting this form does not create an attorney-client relationship, engineering engagement, project approval, regulatory submission, or authorization to proceed. <a href="/privacy" target="_blank" rel="noreferrer">Privacy notice</a>.</p><div aria-live="assertive">{error&&<p className="form-error" role="alert">{error}</p>}</div><div className="actions"><button className="button primary" type="submit" disabled={state==='submitting'}>{state==='submitting'?'Submitting…':'Submit request'}</button><button className="button secondary" type="button" onClick={close} disabled={state==='submitting'}>Cancel</button></div></form></>}
 </section></div>
}
